CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(160) NOT NULL,
    website VARCHAR(500) NULL,
    company_type VARCHAR(20) NOT NULL,
    industry VARCHAR(120) NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id),
    CONSTRAINT ck_companies_company_type CHECK (
        company_type IN ('STARTUP', 'SCALEUP', 'CORPORATE', 'CONSULTING', 'OTHER')
    )
);

CREATE INDEX ix_companies_name ON companies (LOWER(name), id);

CREATE TABLE job_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_job_sources PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_job_sources_name ON job_sources (LOWER(name));

CREATE TABLE technologies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_technologies PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_technologies_name ON technologies (LOWER(name));

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id BIGINT NOT NULL,
    position_title VARCHAR(180) NOT NULL,
    job_url VARCHAR(1000) NULL,
    applied_date DATE NULL,
    -- Intentional denormalization of the current status. The application service
    -- must update this value and append status history in the same transaction.
    status VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    work_mode VARCHAR(16) NOT NULL,
    location VARCHAR(160) NULL,
    salary_min NUMERIC(19, 2) NULL,
    salary_max NUMERIC(19, 2) NULL,
    currency VARCHAR(3) NULL,
    salary_period VARCHAR(16) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_job_applications PRIMARY KEY (id),
    CONSTRAINT fk_job_applications_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_job_applications_source FOREIGN KEY (source_id) REFERENCES job_sources (id),
    CONSTRAINT ck_job_applications_status CHECK (
        status IN (
            'BOOKMARKED', 'APPLIED', 'RESPONSE_RECEIVED', 'HR_INTERVIEW',
            'TECHNICAL_INTERVIEW', 'FINAL_INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN'
        )
    ),
    CONSTRAINT ck_job_applications_work_mode CHECK (work_mode IN ('REMOTE', 'HYBRID', 'ONSITE')),
    CONSTRAINT ck_job_applications_salary_period CHECK (
        salary_period IS NULL OR salary_period IN ('YEARLY', 'MONTHLY', 'HOURLY')
    ),
    CONSTRAINT ck_job_applications_salary_non_negative CHECK (
        (salary_min IS NULL OR salary_min >= 0) AND (salary_max IS NULL OR salary_max >= 0)
    ),
    CONSTRAINT ck_job_applications_salary_range CHECK (
        salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min
    ),
    CONSTRAINT ck_job_applications_salary_metadata CHECK (
        (
            salary_min IS NULL AND salary_max IS NULL
            AND currency IS NULL AND salary_period IS NULL
        )
        OR
        (
            (salary_min IS NOT NULL OR salary_max IS NOT NULL)
            AND currency IS NOT NULL AND salary_period IS NOT NULL
        )
    )
);

CREATE INDEX ix_job_applications_status_applied_date
    ON job_applications (status, applied_date DESC);
CREATE INDEX ix_job_applications_source_id ON job_applications (source_id);
CREATE INDEX ix_job_applications_company_id ON job_applications (company_id);
CREATE INDEX ix_job_applications_created_at ON job_applications (created_at DESC);

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    changed_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_application_status_history PRIMARY KEY (id),
    CONSTRAINT fk_status_history_application FOREIGN KEY (application_id)
        REFERENCES job_applications (id) ON DELETE CASCADE,
    CONSTRAINT ck_status_history_status CHECK (
        status IN (
            'BOOKMARKED', 'APPLIED', 'RESPONSE_RECEIVED', 'HR_INTERVIEW',
            'TECHNICAL_INTERVIEW', 'FINAL_INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN'
        )
    )
);

CREATE INDEX ix_status_history_application_changed_at
    ON application_status_history (application_id, changed_at);
CREATE INDEX ix_status_history_status_application
    ON application_status_history (status, application_id);

CREATE TABLE job_application_technologies (
    application_id BIGINT NOT NULL,
    technology_id BIGINT NOT NULL,
    CONSTRAINT pk_job_application_technologies PRIMARY KEY (application_id, technology_id),
    CONSTRAINT fk_application_technologies_application FOREIGN KEY (application_id)
        REFERENCES job_applications (id) ON DELETE CASCADE,
    CONSTRAINT fk_application_technologies_technology FOREIGN KEY (technology_id)
        REFERENCES technologies (id)
);

CREATE INDEX ix_application_technologies_technology_application
    ON job_application_technologies (technology_id, application_id);
