CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NULL,
    google_subject VARCHAR(255) NULL,
    email_verified_at TIMESTAMP(3) WITH TIME ZONE NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_users_email ON users (LOWER(email));
CREATE UNIQUE INDEX ux_users_google_subject ON users (google_subject) WHERE google_subject IS NOT NULL;

CREATE TABLE account_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP(3) WITH TIME ZONE NULL,
    CONSTRAINT pk_account_tokens PRIMARY KEY (id),
    CONSTRAINT fk_account_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_account_tokens_purpose CHECK (
        purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'PASSWORD_SETUP')
    )
);

CREATE UNIQUE INDEX ux_account_tokens_hash ON account_tokens (token_hash);
CREATE INDEX ix_account_tokens_user_purpose
    ON account_tokens (user_id, purpose, consumed_at, expires_at);

CREATE TABLE spring_session (
    primary_id CHAR(36) NOT NULL,
    session_id CHAR(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INT NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(254),
    CONSTRAINT pk_spring_session PRIMARY KEY (primary_id)
);

CREATE UNIQUE INDEX spring_session_ix1 ON spring_session (session_id);
CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE spring_session_attributes (
    session_primary_id CHAR(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    CONSTRAINT pk_spring_session_attributes PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT fk_spring_session_attributes FOREIGN KEY (session_primary_id)
        REFERENCES spring_session (primary_id) ON DELETE CASCADE
);

-- The database is intentionally empty at this product-phase boundary, so ownership
-- can be enforced immediately without an ambiguous legacy-data backfill.
ALTER TABLE companies ADD COLUMN owner_id BIGINT NOT NULL;
ALTER TABLE companies ADD CONSTRAINT fk_companies_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);
ALTER TABLE companies ADD CONSTRAINT uq_companies_id_owner UNIQUE (id, owner_id);
DROP INDEX ix_companies_name;
CREATE INDEX ix_companies_owner_name ON companies (owner_id, LOWER(name), id);

ALTER TABLE job_applications ADD COLUMN owner_id BIGINT NOT NULL;
ALTER TABLE job_applications ADD CONSTRAINT fk_job_applications_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);
ALTER TABLE job_applications DROP CONSTRAINT fk_job_applications_company;
ALTER TABLE job_applications ADD CONSTRAINT fk_job_applications_company_owner
    FOREIGN KEY (company_id, owner_id) REFERENCES companies (id, owner_id);

DROP INDEX ix_job_applications_status_applied_date;
DROP INDEX ix_job_applications_source_id;
DROP INDEX ix_job_applications_company_id;
DROP INDEX ix_job_applications_created_at;
CREATE INDEX ix_job_applications_owner_status_applied_date
    ON job_applications (owner_id, status, applied_date DESC);
CREATE INDEX ix_job_applications_owner_source_id
    ON job_applications (owner_id, source_id);
CREATE INDEX ix_job_applications_owner_company_id
    ON job_applications (owner_id, company_id);
CREATE INDEX ix_job_applications_owner_created_at
    ON job_applications (owner_id, created_at DESC);

ALTER TABLE technologies ADD COLUMN owner_id BIGINT NULL;
ALTER TABLE technologies ADD CONSTRAINT fk_technologies_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);
DROP INDEX ux_technologies_name;
CREATE UNIQUE INDEX ux_technologies_shared_name
    ON technologies (LOWER(name)) WHERE owner_id IS NULL;
CREATE UNIQUE INDEX ux_technologies_owner_name
    ON technologies (owner_id, LOWER(name)) WHERE owner_id IS NOT NULL;
CREATE INDEX ix_technologies_owner_name
    ON technologies (owner_id, LOWER(name), id);
